### ISSUE TITLE
not working with cordova 6.x on ios.

### ISSUE THREAD

**Issue by midorikocak** [gbenvenuti/cordova-plugin-screen-orientation#96]
lock orientation is totally broken.
also screen.orienatations all returned wrong

**Comment by gabrielezereik** [comment]
In my app, with cordova 6.x, orientation is detected only in portrait modes (either primary and secondary), but, the "orientationchange" event is not fired when orientation is changed to landscape.

**Comment by lovelyelfpop** [comment]
I have the same problem

**Comment by gwleandro** [comment]
Me too, any solution ?

**Comment by xgzl87** [comment]
I have the same problem

**Comment by enckecr** [comment]
I had a similar issue on a new version, the solution was to be sure all orientation methods are enabled in the plist (or GUI).

Matthew

**Comment by raykin** [comment]
@enckecr  could you show me how to edit plist to fix it?
I enabled all Device Orientation and Requires full screen in xcode but it doesn't work

**Comment by enckecr** [comment]
<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>

**Comment by raykin** [comment]
@enckecr  doesn't work on my app. The page flicker to landscape then back to original orientation. Don't know why.

**Comment by enckecr** [comment]
Make sure that you are running it after the "device ready" event.

screen.lockOrientation( "landscape" );

Also, it is always good to wrap these events with a timeout

window.setTimeout( function() { screen.lockOrientation( "landscape" ); }, 0 );

**Comment by raykin** [comment]
@enckecr  i can even debug it in safari console with screen.***function***,  but just not work. If the screen is not exist, it will through error like undefined has no function. But when I debug, no error happened.

**Comment by enckecr** [comment]
Add this line after setting the orientation

console.log( screen );

**Comment by raykin** [comment]
@enckecr  return Screen {lockOrientation: function, unlockOrientation: function, orientation: "portrait-primary", height: 667, width: 375, …}

**Comment by raykin** [comment]
Since many guys said it's not worked in ios9.3, so I guess there are some trick in ios9.3 self, not in the plugin. But the fix may require a workaround by editing plugin.

**Comment by enckecr** [comment]
run it like this, before and after the orientation change and look at the difference, the "orientation" value should change.

console.log( screen.orientation );
screen.lockOrientation( "landscape" );
console.log( screen.orientation );

**Comment by raykin** [comment]
@enckecr  not changed. 
```
console.log( screen.orientation );
portrait-primary
screen.lockOrientation( "landscape" );
undefined
console.log( screen.orientation );
portrait-primary
```

**Comment by raykin** [comment]
@enckecr  just as I said, there is a orientation flicker then back to origin

**Comment by enckecr** [comment]
Try installing the plugin from the GIT url and not form the NPM.

cordova plugin rm cordova-plugin-screen-orientation
cordova plugin add https://github.com/gbenvenuti/cordova-plugin-screen-orientation.git

Then try the same console.log code with the changes to see if that fixes it. In the notes on #89 (https://github.com/gbenvenuti/cordova-plugin-screen-orientation/pull/89 <https://github.com/gbenvenuti/cordova-plugin-screen-orientation/pull/89>), we see a note that they  have some issues with the update in the NPM

Matthew

**Comment by raykin** [comment]
I'm already use the git url for this plugin.
```zsh
➜  kasa git:(master) cat package.json | ag orientation
      "locator": "https://github.com/gbenvenuti/cordova-plugin-screen-orientation",
      "id": "cordova-plugin-screen-orientation"
```

**Comment by gbenvenuti** [comment]
Hi all, 

Thanks to @tony-- there's now a PR in progress, you can install the development version for testing, please removed existing plugin first

    cordova plugin add https://github.com/gbenvenuti/cordova-plugin-screen-orientation.git#iosTesting

It currently does not unlock but if you are interested in testing please do so.

**Comment by atorger** [comment]
I have the same problem as raykin, the official release will not lock screen at all on iOS, but when installing cordova plugin add https://github.com/gbenvenuti/cordova-plugin-screen-orientation.git#iosTesting
it does work to lock the orientation, although "portrait" is the same as "portrait-primary", and as said it's not possible to unlock it again.

**Comment by atorger** [comment]
Found a small bug in plugin.xml in #iosTesting, the file "src/ios/CDVViewController+UpdateSupportedOrientations.h" is marked as a source file rather than a header file. It only causes a compile warning in XCode so I think it's not harmful, but to get rid of that just change source-file to header-file for that entry in plugin.xml.

**Comment by arendjantetteroo** [comment]
@atorger does the event fire for you? I use the event to setup the view, so calendar week view for landscape and day view for portrait. On flipping the phone i want to switch views. This is no longer working as the event is not firing in ios.

**Comment by atorger** [comment]
@arendjantetteroo , I haven't checked, but if it doesn't work for you it probably doesn't for me. I was lucky enough to have a very simple use case in my app: "at startup: if small screen permanently lock the orientation to portrait, otherwise leave unlocked.", so I don't need the events to work, just the locking.

**Comment by tony--** [comment]
Thanks @atorger!  I fixed the declaration.

**Comment by tony--** [comment]
@midorikocak - @gbenvenuti has released 1.4.2 which should fix this issue. Will you try 1.4.2 and provide an update, please?

**Comment by arendjantetteroo** [comment]
@tony--  The orientationchange event still does not fire for me on 1.4.2. Any idea what i can do about that?

**Comment by arendjantetteroo** [comment]
@tony--  Ok, it is working if you make sure the Device orientation has all 4 items checked, otherwise the event won't fire. Might be good to add that to the Readme on the Event Listener.

**Comment by tony--** [comment]
@arendjantetteroo - In my testing I did not directly modify the plist to change supported orientations, but I did test different Cordova Orientation preference settings (which causes the supported orientations in the plist to be modified).  You should not need to enable all the orientations in XCode.  My default test case was an unmodified Cordova app which is portrait only, but I also tested with Landscape and All - a few others in other Issue/PR conversations had trouble with their existing apps but success with a clean app.

Could you try with a clean app?
```
cordova create screen-orientation-test
cd screen-orientation-test
cordova platform add ios@4.1.1
cordova plugin add https://github.com/tony--/cordova-plugin-screen-orientation#fix-ios-rotate-on-lock
cordova run ios
```
The test app should start in portrait and not auto-rotate.
Using Safari Web Inspector Console
```
screen.lockOrientation('landscape') 
//should rotate to landscape left and should auto-rotate between landscape orientations
screen.unlockOrientation()
//should rotate to portrait and no longer auto-rotate when device is tilted

**Comment by arendjantetteroo** [comment]
@tony-- Thanks for the reply, i'll try to take a look at the clean app. 

I'm glad it's working again with the plist changes though :)

**Comment by tony--** [comment]
AFAIK this issue is resolved so I'm going to close this.
OP or other commenters - please provide additional feedback if this issue is not resolved for you.

**Comment by crtvhd** [comment]
If it helps anyone: we fixed the issue, which occurred after upgrading to cordova 6, by adding the following lines to our `config.xml`:

```xml
<platform name="ios">
  <preference name="Orientation" value="all" />
</platform>
```

**Comment by tony--** [comment]
Thanks @crtvhd.
